---
# tasks file for composer
- include: setup.yml
  become: yes
  become_user: root

- name: install global packages for php
  shell: "composer global require {{ item }}"
  with_items:
    - hirak/prestissimo
