---
# tasks file for git
- name: Splat in the git config
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Splat in the global gitignore
  template:
    src: gitignore.j2
    dest: "{{ ansible_env.HOME }}/.gitignore"

- name: Splat in the git commit message template
  copy:
    src: gitmessage
    dest: "{{ ansible_env.HOME }}/.gitmessage"

#- name: Add git-core PPA
#  apt_repository:
#    repo: 'ppa:git-core/ppa'
#    update_cache: yes

- name: Install supporting packages
  apt:
    name: "{{ item }}"
  with_items:
    - gitg
    - nano
#    - git
